apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: banka-4-ingress-api
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
        - pathType: ImplementationSpecific
          path: "/user-service(/|$)(.*)"
          backend:
            service:
              name: user-service
              port:
                number: 8080
        - pathType: ImplementationSpecific
          path: "/banka-service(/|$)(.*)"
          backend:
            service:
              name: banka-service
              port:
                number: 8082
        - pathType: ImplementationSpecific
          path: "/berza-service(/|$)(.*)"
          backend:
            service:
              name: berza-servis
              port:
                number: 8081