apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: banka-4-ingress-frontend
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: frontend
              port:
                number: 80